# Generated by Django 3.1.13 on 2021-08-19 07:00

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=photo.fields.ThumbnailImageField(null=True, upload_to='blog/%Y/%m', verbose_name='IMAGE'),
        ),
    ]
